use_frameworks!

source 'https://github.com/ibroadlink/BLLibSpecs.git'

target 'BLLetAsync_Example' do
  pod 'BLLetAsync', :path => '../'

  target 'BLLetAsync_Tests' do
    inherit! :search_paths

    
  end
end
